0Eo     o                                  .oPYo. 
8b   d8                                  8      
8`b d'8 .oPYo. odYo. .oPYo. oPYo. .oPYo. `Yooo. 
8 `o' 8 8    8 8' `8 8oooo8 8  `' 8    8     `8 
8     8 8    8 8   8 8.     8     8    8      8 
8     8 `YooP' 8   8 `Yooo' 8     `YooP' `YooP' 0F

Author: David Sin @ 2022 Christmas
MoneroS is distributed with ABSOLUTELY NO WARRANTY.

Please make sure that your internet cable is connected.
Press <Enter> to begin mining or wait for 5 seconds.
